# Generated by Django 5.0 on 2023-12-30 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_setor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFuncionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_convenio', models.CharField(max_length=255)),
                ('parlamentar', models.CharField(max_length=255)),
                ('objeto', models.CharField(max_length=255)),
                ('oge_ogu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cp_prefeitura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_liberado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prazo_vigencia', models.DateField()),
                ('situacao', models.CharField(max_length=255)),
                ('providencia', models.CharField(max_length=255)),
                ('data_recepcao', models.DateField()),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('documento_pendente', models.BooleanField(default=False)),
                ('documento_cancelado', models.BooleanField(default=False)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('duracao_dias_uteis', models.IntegerField(default=0)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.atividade')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.municipio')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.nome')),
                ('orgao_setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.setor')),
            ],
        ),
    ]
