# Generated by Django 5.0 on 2024-01-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='registrofuncionarios',
            name='status',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_analise', 'Em Análise'), ('pendente', 'Pendente'), ('suspenso', 'Suspenso'), ('concluido', 'Concluído')], default='nao_iniciado', max_length=20),
        ),
    ]
