# Generated by Django 5.0 on 2024-01-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_registrofuncionarios_falta_liberar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrofuncionarios',
            name='falta_liberar',
        ),
        migrations.RemoveField(
            model_name='registrofuncionarios',
            name='valor_total',
        ),
    ]
