# Generated by Django 5.0 on 2024-01-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_remove_registrofuncionarios_falta_liberar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrofuncionarios',
            options={'verbose_name_plural': 'Registros de Funcionários'},
        ),
        migrations.AddField(
            model_name='registrofuncionarios',
            name='falta_liberar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='registrofuncionarios',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
