# Generated by Django 5.0 on 2024-01-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_registrofuncionarios_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrofuncionarios',
            name='falta_liberar',
        ),
        migrations.RemoveField(
            model_name='registrofuncionarios',
            name='valor_total',
        ),
    ]
