# Generated by Django 5.0 on 2024-01-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_remove_registrofuncionarios_falta_liberar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofuncionarios',
            name='status',
            field=models.CharField(choices=[('Não Iniciado', 'Não Iniciado'), ('Em Análise', 'Em Análise'), ('Pendente', 'Pendente'), ('Suspenso', 'Suspenso'), ('Concluído', 'Concluído')], default='Não Iniciado', max_length=20),
        ),
    ]
