# Generated by Django 5.0 on 2024-01-10 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_alter_registrofuncionarios_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dados_anteriores', models.JSONField(default=dict)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.registrofuncionarios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
