# Generated by Django 5.0 on 2024-01-10 19:02

import plataforma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='dados_anteriores',
            field=models.JSONField(default=dict, encoder=plataforma.models.DecimalJSONEncoder),
        ),
    ]
