# Generated by Django 5.0 on 2024-01-27 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_alter_historico_dados_anteriores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrofuncionarios',
            options={'verbose_name_plural': 'Registros da Tabela Geral'},
        ),
        migrations.CreateModel(
            name='RegistroReceitaFederal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parcelamento', models.IntegerField()),
                ('objeto', models.CharField(max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo_vigencia', models.DateField()),
                ('situacao', models.CharField(max_length=255)),
                ('providencia', models.CharField(max_length=255)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.atividade')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.municipio')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.nome')),
            ],
            options={
                'verbose_name_plural': 'Tabela da Receita Federal',
            },
        ),
    ]
