# Generated by Django 5.0 on 2024-01-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_alter_registrofuncionarios_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFGTSIndCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=255)),
                ('nome_empregado', models.CharField(max_length=255)),
                ('pis', models.IntegerField()),
                ('admissao', models.DateField()),
                ('afastamento', models.DateField()),
                ('cod_afastamento', models.IntegerField()),
                ('fgts', models.IntegerField()),
                ('gfip', models.IntegerField()),
                ('folha_de_pagamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arbitrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recomposto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rem_debito', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Tabela de FGTS, Individualização e Contabilidade',
            },
        ),
    ]
