# Generated by Django 5.0.2 on 2024-02-19 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_registroadminstracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofgtsindcon',
            name='pis',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(10000000000)]),
        ),
    ]
