# Generated by Django 5.0.4 on 2024-04-19 12:54

import plataforma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_alter_registrofgtsindcon_pis'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='dados_atuais',
            field=models.JSONField(default=dict, encoder=plataforma.models.DecimalJSONEncoder),
        ),
    ]
