# Generated by Django 5.0.4 on 2024-04-24 18:08

import plataforma.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_historico_dados_atuais'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='dados_alterados',
            field=models.JSONField(default=dict, encoder=plataforma.models.DecimalJSONEncoder),
        ),
    ]
